version: '3.3'

services:
  composer:
    build: ./docker/composer
    volumes:
      - .:/app

  tests:
    build: ./docker/tests
    working_dir: /app
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    volumes:
      - .:/app
    entrypoint: ./vendor/bin/phpunit --bootstrap vendor/autoload.php
    command: ['tests']
